spring.application.name=transaction-service
server.port=9090
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/transaction
spring.datasource.username=hanshulchandel
spring.datasource.password=

# Disable Hibernate schema generation to let Flyway handle it
spring.jpa.hibernate.ddl-auto=validate
# Optional: Flyway specific configurations
spring.flyway.enabled=false
logging.level.org.flywaydb=DEBUG
