global:
  scrape_interval: 5s

scrape_configs:
  - job_name: ledger-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ledger-app:8080"]

  - job_name: ledger-consumer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ledger-consumer:8081"]
